name: Smartmine
version: 0.4.44
description: This is the Floriware Smartmine Plugin (Build 30.11.2012).
author: Florian Schiessl
website: minecraft.floriware.eu

main: eu.floriware.minecraft.Smartmine.Smartmine
database: false

commands:
    smreloadconf:
        description: Reloads Smartmine configuration from file.
        usage: /smreloadconf
