name: Smartmine
version: 0.5.0
api-version: 1.20
description: This is the Floriware Smartmine Plugin (Build 2.12.2023).
author: Florian Schiessl
website: minecraft.floriware.eu

main: eu.floriware.minecraft.Smartmine.Smartmine
database: false

commands:
    smreloadconf:
        description: Reloads Smartmine configuration from file.
        usage: /smreloadconf
